version: '3.8'
services:
  postgres:
    container_name: keycloak-db
    env_file:
      - ./keycloak-postgres.env
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - keycloak-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    env_file:
      - ./keycloak-postgres.env
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - keycloak-network
    depends_on:
      - postgres
networks:
  keycloak-network:
    driver: bridge
